version: "3"

services:
  tweet_app:
    build: ./tweet-app/
    command: bash -c "yarn start"
    volumes:
      - ./tweet-app:/tweet-app
    ports:
      - "3000:3000"
    hostname: tweet_app

  react_twitter_clone:
    build: ./react-twitter-clone/
    command: bash -c "yarn start"
    volumes:
      - ./react-twitter-clone:/react-twitter-clone
    ports:
      - "3001:3001"
    hostname: react-twitter-clone

  db:
    image: postgres
    environment:
      - POSTGRES_DB=django_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django_api:
    build: ./django_api/
    volumes:
    - ./django_api:/django_api
    ports:
    - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - USE_DOCKER=True
