version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django_api:
    build: ./django_api/
    volumes:
    - ./django_api:/django_api
    ports:
    - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db